services:
  mysql:
    image: mysql:9.5.0
    container_name: restaurant_booking
    environment:
      MYSQL_DATABASE: restaurant_demo_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: